# Generated by Django 5.1 on 2024-12-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(verbose_name="slug")),
                ("photo", models.URLField(verbose_name="photo")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "palestrante",
                "verbose_name_plural": "palestrantes",
            },
        ),
    ]
