# Generated by Django 5.1 on 2024-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=600, verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, max_length=600, verbose_name='resposta'),
        ),
    ]
